name: Update Docs

on:
  push:
    branches-ignore:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run make command

        run: |
          make generate

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'generate documentation'
          add: '.'
